"""initial schema

Revision ID: b82f64d95af3
Revises:
Create Date: 2026-06-04 16:09:28.147479

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b82f64d95af3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('node_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_messages_reason'), 'dead_letter_messages', ['reason'], unique=False)
    op.create_table('inbox_messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('step_run_id', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_run_id', 'attempt', name='uq_inbox_step_attempt')
    )
    op.create_index(op.f('ix_inbox_messages_step_run_id'), 'inbox_messages', ['step_run_id'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('delivery_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id', name='uq_outbox_delivery')
    )
    op.create_index(op.f('ix_outbox_messages_run_id'), 'outbox_messages', ['run_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_status'), 'outbox_messages', ['status'], unique=False)
    op.create_index('ix_outbox_status_created', 'outbox_messages', ['status', 'created_at'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('definition_key', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('business_ref', sa.String(length=255), nullable=True),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('definition_revision', sa.String(length=64), nullable=True),
    sa.Column('pipeline_version', sa.String(length=16), nullable=False),
    sa.Column('compiled_graph_version', sa.String(length=16), nullable=False),
    sa.Column('runtime_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('outputs_spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('definition_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('completion_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_definition_key'), 'workflow_instances', ['definition_key'], unique=False)
    op.create_index(op.f('ix_workflow_instances_idempotency_key'), 'workflow_instances', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_workflow_instances_run_id'), 'workflow_instances', ['run_id'], unique=True)
    op.create_index(op.f('ix_workflow_instances_status'), 'workflow_instances', ['status'], unique=False)
    op.create_table('execution_edges',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('from_key', sa.String(length=64), nullable=False),
    sa.Column('to_key', sa.String(length=64), nullable=False),
    sa.Column('edge_kind', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_edges_instance_id'), 'execution_edges', ['instance_id'], unique=False)
    op.create_table('execution_nodes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('transport_mode', sa.String(length=32), nullable=False),
    sa.Column('on_failure', sa.String(length=16), nullable=False),
    sa.Column('retry_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('valid_for_sec', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('middlewares', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('depends_on', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('step_run_id', sa.String(length=64), nullable=True),
    sa.Column('delivery_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('compensation_status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'node_key', name='uq_node_key')
    )
    op.create_index(op.f('ix_execution_nodes_deadline_at'), 'execution_nodes', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_execution_nodes_instance_id'), 'execution_nodes', ['instance_id'], unique=False)
    op.create_index(op.f('ix_execution_nodes_status'), 'execution_nodes', ['status'], unique=False)
    op.create_index(op.f('ix_execution_nodes_step_run_id'), 'execution_nodes', ['step_run_id'], unique=False)
    op.create_table('join_states',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('expected', sa.Integer(), nullable=False),
    sa.Column('arrived', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_states_instance_id'), 'join_states', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_join_states_instance_id'), table_name='join_states')
    op.drop_table('join_states')
    op.drop_index(op.f('ix_execution_nodes_step_run_id'), table_name='execution_nodes')
    op.drop_index(op.f('ix_execution_nodes_status'), table_name='execution_nodes')
    op.drop_index(op.f('ix_execution_nodes_instance_id'), table_name='execution_nodes')
    op.drop_index(op.f('ix_execution_nodes_deadline_at'), table_name='execution_nodes')
    op.drop_table('execution_nodes')
    op.drop_index(op.f('ix_execution_edges_instance_id'), table_name='execution_edges')
    op.drop_table('execution_edges')
    op.drop_index(op.f('ix_workflow_instances_status'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_run_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_idempotency_key'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_definition_key'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index('ix_outbox_status_created', table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_status'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_run_id'), table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_inbox_messages_step_run_id'), table_name='inbox_messages')
    op.drop_table('inbox_messages')
    op.drop_index(op.f('ix_dead_letter_messages_reason'), table_name='dead_letter_messages')
    op.drop_table('dead_letter_messages')
    # ### end Alembic commands ###
